# -*- coding: utf-8 -*-

"""
maxioadvancedbillingformerlychargifyapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

import json
import dateutil.parser

from tests.controllers.controller_test_base import ControllerTestBase
from apimatic_core.utilities.comparison_helper import ComparisonHelper
from maxioadvancedbillingformerlychargifyapi.api_helper import APIHelper
from maxioadvancedbillingformerlychargifyapi.models.enable_webhooks_request import EnableWebhooksRequest
from maxioadvancedbillingformerlychargifyapi.models.replay_webhooks_request import ReplayWebhooksRequest
from maxioadvancedbillingformerlychargifyapi.models.update_endpoint_request import UpdateEndpointRequest


class WebhooksControllerTests(ControllerTestBase):

    @classmethod
    def setUpClass(cls):
        super(WebhooksControllerTests, cls).setUpClass()
        cls.controller = cls.client.webhooks
        cls.response_catcher = cls.controller.http_call_back

    # ## Webhooks Intro
    #
    #The Webhooks API allows you to view a list of all webhooks and to selectively resend individual or groups of webhooks. Webhooks will be sent on endpoints specified by you. Endpoints can be added via API or Web UI. There is also an option to enable / disable webhooks via API request.
    #
    #We recommend that you review Chargify's webhook documentation located in our help site. The following resources will help guide you on how to use webhooks in Chargify, in addition to these webhook endpoints:
    #
    #+ [Adding/editing new webhooks](https://maxio-chargify.zendesk.com/hc/en-us/articles/5404448450317#configure-webhook-url)
    #+ [Webhooks introduction and delivery information](https://maxio-chargify.zendesk.com/hc/en-us/articles/5405568068365#webhooks-introduction-0-0)
    #+ [Main webhook overview](https://maxio-chargify.zendesk.com/hc/en-us/articles/5405357509645-Webhooks-Reference#webhooks-reference-0-0)
    #+ [Available webhooks and payloads](https://maxio-chargify.zendesk.com/hc/en-us/articles/5405357509645-Webhooks-Reference#events)
    #
    ### List Webhooks for a Site
    #
    #This method allows you to fetch data about webhooks. You can pass query parameters if you want to filter webhooks.
    def test_list_webhooks(self):
        # Parameters for the API call
        status = None
        since_date = None
        until_date = None
        page = 1
        per_page = 20
        order = None
        subscription = None

        # Perform the API call through the SDK function
        result = self.controller.list_webhooks(status, since_date, until_date, page, per_page, order, subscription)

        # Test response code
        assert self.response_catcher.response.status_code == 201

        # Test headers
        expected_headers = {}
        expected_headers['content-type'] = 'application/json'

        assert ComparisonHelper.match_headers(expected_headers, self.response_catcher.response.headers)

        
        # Test whether the captured response is as we expected
        assert result is not None
        expected_body = APIHelper.json_deserialize('[{"webhook":{"event":"statement_settled","id":141765032,"created_a'
            't":"2016-11-08T16:22:26-05:00","last_error":"404 Resource Not Foun'
            'd (retry 5 of 5)","last_error_at":"2016-11-08T16:43:54-05:00","acc'
            'epted_at":null,"last_sent_at":"2016-11-08T16:43:54-05:00","last_se'
            'nt_url":"http://requestb.in/11u45x71","successful":false,"body":"i'
            'd=141765032&event=statement_settled&payload[site][id]=31615&payloa'
            'd[site][subdomain]=general-goods&payload[subscription][id]=1510014'
            '1&payload[subscription][state]=active&payload[subscription][balanc'
            'e_in_cents]=0&payload[customer][id]=14585695&payload[customer][fir'
            'st_name]=Pookie&payload[customer][last_name]=Test&payload[customer'
            '][reference]=&payload[customer][organization]=&payload[customer][a'
            'ddress]=&payload[customer][address_2]=&payload[customer][city]=&pa'
            'yload[customer][state]=&payload[customer][zip]=&payload[customer]['
            'country]=&payload[customer][email]=pookie999%40example.com&payload'
            '[customer][phone]=&payload[statement][closed_at]=2016-11-08%2016%3'
            'A22%3A20%20-0500&payload[statement][created_at]=2016-11-08%2016%3A'
            '22%3A18%20-0500&payload[statement][id]=80168049&payload[statement]'
            '[opened_at]=2016-11-07%2016%3A22%3A15%20-0500&payload[statement][s'
            'ettled_at]=2016-11-08%2016%3A22%3A20%20-0500&payload[statement][su'
            'bscription_id]=15100141&payload[statement][updated_at]=2016-11-08%'
            '2016%3A22%3A20%20-0500&payload[statement][starting_balance_in_cent'
            's]=0&payload[statement][ending_balance_in_cents]=0&payload[stateme'
            'nt][total_in_cents]=6400&payload[statement][memo]=We%20thank%20you'
            '%20for%20your%20continued%20business!&payload[statement][events][0'
            '][id]=346956565&payload[statement][events][0][key]=renewal_success'
            '&payload[statement][events][0][message]=Successful%20renewal%20for'
            '%20Pookie%20Test\'s%20subscription%20to%20%2410%20Basic%20Plan&pay'
            'load[statement][events][1][id]=346956579&payload[statement][events'
            '][1][key]=payment_success&payload[statement][events][1][message]=S'
            'uccessful%20payment%20of%20%2464.00%20for%20Pookie%20Test\'s%20sub'
            'scription%20to%20%2410%20Basic%20Plan&payload[statement][events][2'
            '][id]=347299359&payload[statement][events][2][key]=renewal_success'
            '&payload[statement][events][2][message]=Successful%20renewal%20for'
            '%20Pookie%20Test\'s%20subscription%20to%20%2410%20Basic%20Plan&pay'
            'load[statement][transactions][0][id]=161537343&payload[statement]['
            'transactions][0][subscription_id]=15100141&payload[statement][tran'
            'sactions][0][type]=Charge&payload[statement][transactions][0][kind'
            ']=baseline&payload[statement][transactions][0][transaction_type]=c'
            'harge&payload[statement][transactions][0][success]=true&payload[st'
            'atement][transactions][0][amount_in_cents]=1000&payload[statement]'
            '[transactions][0][memo]=%2410%20Basic%20Plan%20(11%2F08%2F2016%20-'
            '%2011%2F09%2F2016)&payload[statement][transactions][0][created_at]'
            '=2016-11-08%2016%3A22%3A18%20-0500&payload[statement][transactions'
            '][0][starting_balance_in_cents]=0&payload[statement][transactions]'
            '[0][ending_balance_in_cents]=1000&payload[statement][transactions]'
            '[0][gateway_used]=&payload[statement][transactions][0][gateway_tra'
            'nsaction_id]=&payload[statement][transactions][0][gateway_order_id'
            ']=&payload[statement][transactions][0][payment_id]=161537369&paylo'
            'ad[statement][transactions][0][product_id]=3792003&payload[stateme'
            'nt][transactions][0][tax_id]=&payload[statement][transactions][0]['
            'component_id]=&payload[statement][transactions][0][statement_id]=8'
            '0168049&payload[statement][transactions][0][customer_id]=14585695&'
            'payload[statement][transactions][0][original_amount_in_cents]=&pay'
            'load[statement][transactions][0][discount_amount_in_cents]=&payloa'
            'd[statement][transactions][0][taxable_amount_in_cents]=&payload[st'
            'atement][transactions][1][id]=161537344&payload[statement][transac'
            'tions][1][subscription_id]=15100141&payload[statement][transaction'
            's][1][type]=Charge&payload[statement][transactions][1][kind]=quant'
            'ity_based_component&payload[statement][transactions][1][transactio'
            'n_type]=charge&payload[statement][transactions][1][success]=true&p'
            'ayload[statement][transactions][1][amount_in_cents]=5400&payload[s'
            'tatement][transactions][1][memo]=Timesheet%20Users%3A%2018%20Times'
            'heet%20Users&payload[statement][transactions][1][created_at]=2016-'
            '11-08%2016%3A22%3A18%20-0500&payload[statement][transactions][1][s'
            'tarting_balance_in_cents]=1000&payload[statement][transactions][1]'
            '[ending_balance_in_cents]=6400&payload[statement][transactions][1]'
            '[gateway_used]=&payload[statement][transactions][1][gateway_transa'
            'ction_id]=&payload[statement][transactions][1][gateway_order_id]=&'
            'payload[statement][transactions][1][payment_id]=161537369&payload['
            'statement][transactions][1][product_id]=3792003&payload[statement]'
            '[transactions][1][tax_id]=&payload[statement][transactions][1][com'
            'ponent_id]=277221&payload[statement][transactions][1][statement_id'
            ']=80168049&payload[statement][transactions][1][customer_id]=145856'
            '95&payload[statement][transactions][1][original_amount_in_cents]=&'
            'payload[statement][transactions][1][discount_amount_in_cents]=&pay'
            'load[statement][transactions][1][taxable_amount_in_cents]=&payload'
            '[statement][transactions][2][id]=161537369&payload[statement][tran'
            'sactions][2][subscription_id]=15100141&payload[statement][transact'
            'ions][2][type]=Payment&payload[statement][transactions][2][kind]=&'
            'payload[statement][transactions][2][transaction_type]=payment&payl'
            'oad[statement][transactions][2][success]=true&payload[statement][t'
            'ransactions][2][amount_in_cents]=6400&payload[statement][transacti'
            'ons][2][memo]=Pookie%20Test%20-%20%2410%20Basic%20Plan%3A%20Renewa'
            'l%20payment&payload[statement][transactions][2][created_at]=2016-1'
            '1-08%2016%3A22%3A20%20-0500&payload[statement][transactions][2][st'
            'arting_balance_in_cents]=6400&payload[statement][transactions][2]['
            'ending_balance_in_cents]=0&payload[statement][transactions][2][gat'
            'eway_used]=bogus&payload[statement][transactions][2][gateway_trans'
            'action_id]=53433&payload[statement][transactions][2][gateway_order'
            '_id]=&payload[statement][transactions][2][payment_id]=&payload[sta'
            'tement][transactions][2][product_id]=3792003&payload[statement][tr'
            'ansactions][2][tax_id]=&payload[statement][transactions][2][compon'
            'ent_id]=&payload[statement][transactions][2][statement_id]=8016804'
            '9&payload[statement][transactions][2][customer_id]=14585695&payloa'
            'd[statement][transactions][2][card_number]=XXXX-XXXX-XXXX-1&payloa'
            'd[statement][transactions][2][card_expiration]=10%2F2020&payload[s'
            'tatement][transactions][2][card_type]=bogus&payload[statement][tra'
            'nsactions][2][refunded_amount_in_cents]=0&payload[product][id]=379'
            '2003&payload[product][name]=%2410%20Basic%20Plan&payload[product_f'
            'amily][id]=527890&payload[product_family][name]=Acme%20Projects&pa'
            'yload[payment_profile][id]=10102821&payload[payment_profile][first'
            '_name]=Pookie&payload[payment_profile][last_name]=Test&payload[pay'
            'ment_profile][billing_address]=&payload[payment_profile][billing_a'
            'ddress_2]=&payload[payment_profile][billing_city]=&payload[payment'
            '_profile][billing_country]=&payload[payment_profile][billing_state'
            ']=&payload[payment_profile][billing_zip]=&payload[event_id]=347299'
            '384","signature":"7c606ec4628ce75ec46e284097ce163a","signature_hma'
            'c_sha_256":"40f25e83dd324508bb2149e3e525821922fb210535ebfbfa81e7ab'
            '951996b41d"}},{"webhook":{"event":"payment_success","id":141765008'
            ',"created_at":"2016-11-08T16:22:25-05:00","last_error":"404 Resour'
            'ce Not Found (retry 5 of 5)","last_error_at":"2016-11-08T16:43:54-'
            '05:00","accepted_at":null,"last_sent_at":"2016-11-08T16:43:54-05:0'
            '0","last_sent_url":"http://requestb.in/11u45x71","successful":fals'
            'e,"body":"id=141765008&event=payment_success&payload[site][id]=316'
            '15&payload[site][subdomain]=general-goods&payload[subscription][id'
            ']=15100141&payload[subscription][state]=active&payload[subscriptio'
            'n][trial_started_at]=&payload[subscription][trial_ended_at]=&paylo'
            'ad[subscription][activated_at]=2016-11-04%2017%3A06%3A43%20-0400&p'
            'ayload[subscription][created_at]=2016-11-04%2017%3A06%3A42%20-0400'
            '&payload[subscription][updated_at]=2016-11-08%2016%3A22%3A22%20-05'
            '00&payload[subscription][expires_at]=&payload[subscription][balanc'
            'e_in_cents]=0&payload[subscription][current_period_ends_at]=2016-1'
            '1-09%2016%3A06%3A42%20-0500&payload[subscription][next_assessment_'
            'at]=2016-11-09%2016%3A06%3A42%20-0500&payload[subscription][cancel'
            'ed_at]=&payload[subscription][cancellation_message]=&payload[subsc'
            'ription][next_product_id]=&payload[subscription][cancel_at_end_of_'
            'period]=false&payload[subscription][payment_collection_method]=aut'
            'omatic&payload[subscription][snap_day]=&payload[subscription][canc'
            'ellation_method]=&payload[subscription][current_period_started_at]'
            '=2016-11-08%2016%3A06%3A42%20-0500&payload[subscription][previous_'
            'state]=active&payload[subscription][signup_payment_id]=161034048&p'
            'ayload[subscription][signup_revenue]=64.00&payload[subscription][d'
            'elayed_cancel_at]=&payload[subscription][coupon_code]=&payload[sub'
            'scription][total_revenue_in_cents]=32000&payload[subscription][pro'
            'duct_price_in_cents]=1000&payload[subscription][product_version_nu'
            'mber]=7&payload[subscription][payment_type]=credit_card&payload[su'
            'bscription][referral_code]=pggn84&payload[subscription][coupon_use'
            '_count]=&payload[subscription][coupon_uses_allowed]=&payload[subsc'
            'ription][customer][id]=14585695&payload[subscription][customer][fi'
            'rst_name]=Test&payload[subscription][customer][last_name]=Test&pay'
            'load[subscription][customer][organization]=&payload[subscription]['
            'customer][email]=pookie999%40example.com&payload[subscription][cus'
            'tomer][created_at]=2016-11-04%2017%3A06%3A42%20-0400&payload[subsc'
            'ription][customer][updated_at]=2016-11-04%2017%3A06%3A45%20-0400&p'
            'ayload[subscription][customer][reference]=&payload[subscription][c'
            'ustomer][address]=&payload[subscription][customer][address_2]=&pay'
            'load[subscription][customer][city]=&payload[subscription][customer'
            '][state]=&payload[subscription][customer][zip]=&payload[subscripti'
            'on][customer][country]=&payload[subscription][customer][phone]=&pa'
            'yload[subscription][customer][portal_invite_last_sent_at]=2016-11-'
            '04%2017%3A06%3A45%20-0400&payload[subscription][customer][portal_i'
            'nvite_last_accepted_at]=&payload[subscription][customer][verified]'
            '=false&payload[subscription][customer][portal_customer_created_at]'
            '=2016-11-04%2017%3A06%3A45%20-0400&payload[subscription][customer]'
            '[cc_emails]=&payload[subscription][product][id]=3792003&payload[su'
            'bscription][product][name]=%2410%20Basic%20Plan&payload[subscripti'
            'on][product][handle]=basic&payload[subscription][product][descript'
            'ion]=lorem%20ipsum&payload[subscription][product][accounting_code]'
            '=basic&payload[subscription][product][request_credit_card]=false&p'
            'ayload[subscription][product][expiration_interval]=&payload[subscr'
            'iption][product][expiration_interval_unit]=never&payload[subscript'
            'ion][product][created_at]=2016-03-24%2013%3A38%3A39%20-0400&payloa'
            'd[subscription][product][updated_at]=2016-11-03%2013%3A03%3A05%20-'
            '0400&payload[subscription][product][price_in_cents]=1000&payload[s'
            'ubscription][product][interval]=1&payload[subscription][product][i'
            'nterval_unit]=day&payload[subscription][product][initial_charge_in'
            '_cents]=&payload[subscription][product][trial_price_in_cents]=&pay'
            'load[subscription][product][trial_interval]=&payload[subscription]'
            '[product][trial_interval_unit]=month&payload[subscription][product'
            '][archived_at]=&payload[subscription][product][require_credit_card'
            ']=false&payload[subscription][product][return_params]=&payload[sub'
            'scription][product][taxable]=false&payload[subscription][product]['
            'update_return_url]=&payload[subscription][product][initial_charge_'
            'after_trial]=false&payload[subscription][product][version_number]='
            '7&payload[subscription][product][update_return_params]=&payload[su'
            'bscription][product][product_family][id]=527890&payload[subscripti'
            'on][product][product_family][name]=Acme%20Projects&payload[subscri'
            'ption][product][product_family][description]=&payload[subscription'
            '][product][product_family][handle]=billing-plans&payload[subscript'
            'ion][product][product_family][accounting_code]=&payload[subscripti'
            'on][product][public_signup_pages][id]=281054&payload[subscription]'
            '[product][public_signup_pages][return_url]=http%3A%2F%2Fwww.exampl'
            'e.com%3Fsuccessfulsignup&payload[subscription][product][public_sig'
            'nup_pages][return_params]=&payload[subscription][product][public_s'
            'ignup_pages][url]=https%3A%2F%2Fgeneral-goods.chargify.com%2Fsubsc'
            'ribe%2Fkqvmfrbgd89q%2Fbasic&payload[subscription][product][public_'
            'signup_pages][id]=281240&payload[subscription][product][public_sig'
            'nup_pages][return_url]=&payload[subscription][product][public_sign'
            'up_pages][return_params]=&payload[subscription][product][public_si'
            'gnup_pages][url]=https%3A%2F%2Fgeneral-goods.chargify.com%2Fsubscr'
            'ibe%2Fdkffht5dxfd8%2Fbasic&payload[subscription][product][public_s'
            'ignup_pages][id]=282694&payload[subscription][product][public_sign'
            'up_pages][return_url]=&payload[subscription][product][public_signu'
            'p_pages][return_params]=&payload[subscription][product][public_sig'
            'nup_pages][url]=https%3A%2F%2Fgeneral-goods.chargify.com%2Fsubscri'
            'be%2Fjwffwgdd95s8%2Fbasic&payload[subscription][credit_card][id]=1'
            '0102821&payload[subscription][credit_card][first_name]=Pookie&payl'
            'oad[subscription][credit_card][last_name]=Test&payload[subscriptio'
            'n][credit_card][masked_card_number]=XXXX-XXXX-XXXX-1&payload[subsc'
            'ription][credit_card][card_type]=bogus&payload[subscription][credi'
            't_card][expiration_month]=10&payload[subscription][credit_card][ex'
            'piration_year]=2020&payload[subscription][credit_card][customer_id'
            ']=14585695&payload[subscription][credit_card][current_vault]=bogus'
            '&payload[subscription][credit_card][vault_token]=1&payload[subscri'
            'ption][credit_card][billing_address]=&payload[subscription][credit'
            '_card][billing_city]=&payload[subscription][credit_card][billing_s'
            'tate]=&payload[subscription][credit_card][billing_zip]=&payload[su'
            'bscription][credit_card][billing_country]=&payload[subscription][c'
            'redit_card][customer_vault_token]=&payload[subscription][credit_ca'
            'rd][billing_address_2]=&payload[subscription][credit_card][payment'
            '_type]=credit_card&payload[subscription][credit_card][site_gateway'
            '_setting_id]=&payload[subscription][credit_card][gateway_handle]=&'
            'payload[transaction][id]=161537369&payload[transaction][subscripti'
            'on_id]=15100141&payload[transaction][type]=Payment&payload[transac'
            'tion][kind]=&payload[transaction][transaction_type]=payment&payloa'
            'd[transaction][success]=true&payload[transaction][amount_in_cents]'
            '=6400&payload[transaction][memo]=Pookie%20Test%20-%20%2410%20Basic'
            '%20Plan%3A%20Renewal%20payment&payload[transaction][created_at]=20'
            '16-11-08%2016%3A22%3A20%20-0500&payload[transaction][starting_bala'
            'nce_in_cents]=6400&payload[transaction][ending_balance_in_cents]=0'
            '&payload[transaction][gateway_used]=bogus&payload[transaction][gat'
            'eway_transaction_id]=53433&payload[transaction][gateway_response_c'
            'ode]=&payload[transaction][gateway_order_id]=&payload[transaction]'
            '[payment_id]=&payload[transaction][product_id]=3792003&payload[tra'
            'nsaction][tax_id]=&payload[transaction][component_id]=&payload[tra'
            'nsaction][statement_id]=80168049&payload[transaction][customer_id]'
            '=14585695&payload[transaction][card_number]=XXXX-XXXX-XXXX-1&paylo'
            'ad[transaction][card_expiration]=10%2F2020&payload[transaction][ca'
            'rd_type]=bogus&payload[transaction][refunded_amount_in_cents]=0&pa'
            'yload[transaction][invoice_id]=&payload[event_id]=347299364","sign'
            'ature":"fbcf2f6be579f9658cff90c4373e0ca2","signature_hmac_sha_256"'
            ':"db96654f5456c5460062feb944ac8bb1418f9d181ae04a8ed982fe9ffdca8de1'
            '"}}]')
        received_body = APIHelper.json_deserialize(self.response_catcher.response.text)
        assert ComparisonHelper.match_body(expected_body, received_body)

    # This method allows you to enable webhooks via API for your site
    def test_enable_webhooks(self):
        # Parameters for the API call
        body = APIHelper.json_deserialize('{"webhooks_enabled":true}', EnableWebhooksRequest.from_dictionary)

        # Perform the API call through the SDK function
        result = self.controller.enable_webhooks(body)

        # Test response code
        assert self.response_catcher.response.status_code == 200

        # Test headers
        expected_headers = {}
        expected_headers['content-type'] = 'application/json'

        assert ComparisonHelper.match_headers(expected_headers, self.response_catcher.response.headers)

        
        # Test whether the captured response is as we expected
        assert result is not None
        expected_body = APIHelper.json_deserialize('{"webhooks_enabled":true}')
        received_body = APIHelper.json_deserialize(self.response_catcher.response.text)
        assert ComparisonHelper.match_body(expected_body, received_body)

    # Posting to the replay endpoint does not immediately resend the webhooks. They are added to a queue and will be sent as soon as possible, depending on available system resources.
    #
    #You may submit an array of up to 1000 webhook IDs to replay in the request.
    def test_replay_webhooks(self):
        # Parameters for the API call
        body = APIHelper.json_deserialize('{"ids":[123456789,123456788]}', ReplayWebhooksRequest.from_dictionary)

        # Perform the API call through the SDK function
        result = self.controller.replay_webhooks(body)

        # Test response code
        assert self.response_catcher.response.status_code == 200

        # Test headers
        expected_headers = {}
        expected_headers['content-type'] = 'application/json'

        assert ComparisonHelper.match_headers(expected_headers, self.response_catcher.response.headers)

        
        # Test whether the captured response is as we expected
        assert result is not None
        expected_body = APIHelper.json_deserialize('{"status":"ok"}')
        received_body = APIHelper.json_deserialize(self.response_catcher.response.text)
        assert ComparisonHelper.match_body(expected_body, received_body)

    # The Chargify API allows you to create an endpoint and assign a list of webhooks subscriptions (events) to it.
    #
    #You can check available events here.
    #[Event keys](https://maxio-chargify.zendesk.com/hc/en-us/articles/5405357509645-Webhooks-Reference#example-payloads)
    def test_create_endpoint(self):
        # Parameters for the API call
        body = APIHelper.json_deserialize('{"endpoint":{"url":"https://your.site/webhooks","webhook_subscript'
            'ions":["payment_success","payment_failure"]}}', UpdateEndpointRequest.from_dictionary)

        # Perform the API call through the SDK function
        result = self.controller.create_endpoint(body)

        # Test response code
        assert self.response_catcher.response.status_code == 200

        # Test headers
        expected_headers = {}
        expected_headers['content-type'] = 'application/json'

        assert ComparisonHelper.match_headers(expected_headers, self.response_catcher.response.headers)

        
        # Test whether the captured response is as we expected
        assert result is not None
        expected_body = APIHelper.json_deserialize('{"endpoint":{"id":1,"url":"https://your.site/webhooks","site_id":1'
            ',"status":"enabled","webhook_subscriptions":["payment_success","pa'
            'yment_failure"]}}')
        received_body = APIHelper.json_deserialize(self.response_catcher.response.text)
        assert ComparisonHelper.match_body(expected_body, received_body)

    # This method returns created endpoints for site.
    def test_list_endpoints(self):

        # Perform the API call through the SDK function
        result = self.controller.list_endpoints()

        # Test response code
        assert self.response_catcher.response.status_code == 200

        # Test headers
        expected_headers = {}
        expected_headers['content-type'] = 'application/json'

        assert ComparisonHelper.match_headers(expected_headers, self.response_catcher.response.headers)

        
        # Test whether the captured response is as we expected
        assert result is not None
        expected_body = APIHelper.json_deserialize('[{"id":11,"url":"https://foobar.com/webhooks","site_id":1,"status"'
            ':"enabled","webhook_subscriptions":["payment_success","payment_fai'
            'lure"]},{"id":12,"url":"https:/example.com/webhooks","site_id":1,"'
            'status":"enabled","webhook_subscriptions":["payment_success","paym'
            'ent_failure","refund_failure"]}]')
        received_body = APIHelper.json_deserialize(self.response_catcher.response.text)
        assert ComparisonHelper.match_body(expected_body, received_body)

