# -*- coding: utf-8 -*-

"""
maxioadvancedbillingformerlychargifyapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

from apimatic_core.types.union_types.any_of import AnyOf
from apimatic_core.types.union_types.leaf_type import LeafType
from apimatic_core.types.union_types.one_of import OneOf
from apimatic_core.types.union_types.union_type_context import UnionTypeContext as Context
from maxioadvancedbillingformerlychargifyapi.models.allocation_payment import AllocationPayment
from maxioadvancedbillingformerlychargifyapi.models.apply_payment_event_data import ApplyPaymentEventData
from maxioadvancedbillingformerlychargifyapi.models.bank_account_payment_profile import BankAccountPaymentProfile
from maxioadvancedbillingformerlychargifyapi.models.cancellation_method_enum import CancellationMethodEnum
from maxioadvancedbillingformerlychargifyapi.models.compounding_strategy_enum import CompoundingStrategyEnum
from maxioadvancedbillingformerlychargifyapi.models.create_component_price_point import CreateComponentPricePoint
from maxioadvancedbillingformerlychargifyapi.models.create_ebb_component import CreateEBBComponent
from maxioadvancedbillingformerlychargifyapi.models.create_metafield import CreateMetafield
from maxioadvancedbillingformerlychargifyapi.models.create_metered_component import CreateMeteredComponent
from maxioadvancedbillingformerlychargifyapi.models.create_on_off_component import CreateOnOffComponent
from maxioadvancedbillingformerlychargifyapi.models.create_or_update_coupon import CreateOrUpdateCoupon
from maxioadvancedbillingformerlychargifyapi.models.create_or_update_flat_amount_coupon import CreateOrUpdateFlatAmountCoupon
from maxioadvancedbillingformerlychargifyapi.models.create_or_update_percentage_coupon import CreateOrUpdatePercentageCoupon
from maxioadvancedbillingformerlychargifyapi.models.create_prepaid_component import CreatePrepaidComponent
from maxioadvancedbillingformerlychargifyapi.models.create_prepaid_usage_component_price_point import CreatePrepaidUsageComponentPricePoint
from maxioadvancedbillingformerlychargifyapi.models.create_quantity_based_component import CreateQuantityBasedComponent
from maxioadvancedbillingformerlychargifyapi.models.create_subscription_component import CreateSubscriptionComponent
from maxioadvancedbillingformerlychargifyapi.models.credit_card_payment_profile import CreditCardPaymentProfile
from maxioadvancedbillingformerlychargifyapi.models.event_data import EventData
from maxioadvancedbillingformerlychargifyapi.models.extended_interval_unit_enum import ExtendedIntervalUnitEnum
from maxioadvancedbillingformerlychargifyapi.models.group_settings import GroupSettings
from maxioadvancedbillingformerlychargifyapi.models.interval_unit_enum import IntervalUnitEnum
from maxioadvancedbillingformerlychargifyapi.models.payment_collection_method_for_subscription_enum import PaymentCollectionMethodForSubscriptionEnum
from maxioadvancedbillingformerlychargifyapi.models.price import Price
from maxioadvancedbillingformerlychargifyapi.models.price_point_type_enum import PricePointTypeEnum
from maxioadvancedbillingformerlychargifyapi.models.pricing_scheme_enum import PricingSchemeEnum
from maxioadvancedbillingformerlychargifyapi.models.refund_consolidated_invoice import RefundConsolidatedInvoice
from maxioadvancedbillingformerlychargifyapi.models.refund_invoice import RefundInvoice
from maxioadvancedbillingformerlychargifyapi.models.resume_options import ResumeOptions
from maxioadvancedbillingformerlychargifyapi.models.snap_day_enum import SnapDayEnum
from maxioadvancedbillingformerlychargifyapi.models.sorting_direction_enum import SortingDirectionEnum
from maxioadvancedbillingformerlychargifyapi.models.subscription_group_inlined import SubscriptionGroupInlined
from maxioadvancedbillingformerlychargifyapi.models.update_metafield import UpdateMetafield


class UnionTypeLookUp:

    """The `UnionTypeLookUp` class serves as a utility class for 
    storing and managing type combinator templates.It acts as a container for the templates 
    used in handling various data types within the application.

    """
    _templates = {
        'CreateCouponBody': OneOf(
            [
                LeafType(CreateOrUpdateCoupon)
            ],
            Context.create(
               is_optional=True
            )
        ),
        'UpdateCouponBody': OneOf(
            [
                LeafType(CreateOrUpdateCoupon)
            ],
            Context.create(
               is_optional=True
            )
        ),
        'CreateComponentBody': OneOf(
            [
                LeafType(CreateMeteredComponent),
                LeafType(CreateQuantityBasedComponent),
                LeafType(CreateOnOffComponent),
                LeafType(CreatePrepaidComponent),
                LeafType(CreateEBBComponent)
            ],
            Context.create(
               is_optional=True
            )
        ),
        'ListAllComponentPricePointsDirection': OneOf(
            [
                LeafType(SortingDirectionEnum)
            ],
            Context.create(
               is_optional=True
            )
        ),
        'ListCustomersDirection': OneOf(
            [
                LeafType(SortingDirectionEnum)
            ],
            Context.create(
               is_optional=True
            )
        ),
        'ListMetafieldsDirection': OneOf(
            [
                LeafType(SortingDirectionEnum)
            ],
            Context.create(
               is_optional=True
            )
        ),
        'ListMetadataDirection': OneOf(
            [
                LeafType(SortingDirectionEnum)
            ],
            Context.create(
               is_optional=True
            )
        ),
        'ReadMrrMovementsDirection': OneOf(
            [
                LeafType(SortingDirectionEnum)
            ],
            Context.create(
               is_optional=True
            )
        ),
        'ListAllProductPricePointsDirection': OneOf(
            [
                LeafType(SortingDirectionEnum)
            ],
            Context.create(
               is_optional=True
            )
        ),
        'ListSubscriptionsInputDirection': OneOf(
            [
                LeafType(SortingDirectionEnum)
            ],
            Context.create(
               is_optional=True
            )
        ),
        'ListSubscriptionComponentsDirection': OneOf(
            [
                LeafType(SortingDirectionEnum)
            ],
            Context.create(
               is_optional=True
            )
        ),
        'ListSubscriptionComponentsForSiteDirection': OneOf(
            [
                LeafType(SortingDirectionEnum)
            ],
            Context.create(
               is_optional=True
            )
        ),
        'SubscriptionCancellationMethod': OneOf(
            [
                LeafType(CancellationMethodEnum)
            ],
            Context.create(
               is_optional=True,
               is_nullable=True
            )
        ),
        'SubscriptionPaymentCollectionMethod': OneOf(
            [
                LeafType(PaymentCollectionMethodForSubscriptionEnum)
            ],
            Context.create(
               is_optional=True,
               is_nullable=True
            )
        ),
        'SubscriptionGroup': OneOf(
            [
                LeafType(SubscriptionGroupInlined)
            ],
            Context.create(
               is_optional=True,
               is_nullable=True
            )
        ),
        'SubscriptionPrepaidDunning': OneOf(
            [
                LeafType(bool)
            ],
            Context.create(
               is_optional=True
            )
        ),
        'ProductExpirationIntervalUnitCase0': OneOf(
            [
                LeafType(ExtendedIntervalUnitEnum)
            ]
        ),
        'ProductExpirationIntervalUnit': OneOf(
            [
                OneOf(
                    [
                        LeafType(ExtendedIntervalUnitEnum)
                    ]
                )
            ],
            Context.create(
               is_optional=True,
               is_nullable=True
            )
        ),
        'ProductIntervalUnit': OneOf(
            [
                LeafType(IntervalUnitEnum)
            ],
            Context.create(
               is_optional=True
            )
        ),
        'ProductTrialIntervalUnitCase0': OneOf(
            [
                LeafType(IntervalUnitEnum)
            ]
        ),
        'ProductTrialIntervalUnit': OneOf(
            [
                OneOf(
                    [
                        LeafType(IntervalUnitEnum)
                    ]
                )
            ],
            Context.create(
               is_optional=True,
               is_nullable=True
            )
        ),
        'CreateMetafieldsRequestMetafields': AnyOf(
            [
                LeafType(CreateMetafield),
                LeafType(CreateMetafield,
                         Context.create(
                             is_array=True
                         ))
            ]
        ),
        'MetafieldEnum': OneOf(
            [
                LeafType(str,
                         Context.create(
                             is_array=True
                         ))
            ],
            Context.create(
               is_array=True,
               is_optional=True,
               is_nullable=True
            )
        ),
        'UpdateMetafieldsRequestMetafields': AnyOf(
            [
                LeafType(UpdateMetafield),
                LeafType(UpdateMetafield,
                         Context.create(
                             is_array=True
                         ))
            ],
            Context.create(
               is_optional=True
            )
        ),
        'CreateOrUpdateCouponCoupon': OneOf(
            [
                LeafType(CreateOrUpdatePercentageCoupon),
                LeafType(CreateOrUpdateFlatAmountCoupon)
            ],
            Context.create(
               is_optional=True
            )
        ),
        'CreateOrUpdateCouponRestrictedProducts': OneOf(
            [
                LeafType(bool,
                         Context.create(
                             is_dict=True
                         ))
            ],
            Context.create(
               is_dict=True,
               is_optional=True
            )
        ),
        'CreateOrUpdateCouponRestrictedComponents': OneOf(
            [
                LeafType(bool,
                         Context.create(
                             is_dict=True
                         ))
            ],
            Context.create(
               is_dict=True,
               is_optional=True
            )
        ),
        'CreateOrUpdatePercentageCouponPercentage': OneOf(
            [
                LeafType(float),
                LeafType(str)
            ]
        ),
        'CreateOrUpdatePercentageCouponCompoundingStrategy': OneOf(
            [
                LeafType(CompoundingStrategyEnum)
            ],
            Context.create(
               is_optional=True
            )
        ),
        'CreateOrUpdateFlatAmountCouponCompoundingStrategy': OneOf(
            [
                LeafType(CompoundingStrategyEnum)
            ],
            Context.create(
               is_optional=True
            )
        ),
        'CouponCompoundingStrategyCase0': OneOf(
            [
                LeafType(CompoundingStrategyEnum)
            ]
        ),
        'CouponCompoundingStrategy': AnyOf(
            [
                OneOf(
                    [
                        LeafType(CompoundingStrategyEnum)
                    ]
                )
            ],
            Context.create(
               is_optional=True
            )
        ),
        'EventEventSpecificData': OneOf(
            [
                LeafType(EventData)
            ],
            Context.create(
               is_nullable=True
            )
        ),
        'MeteredComponentPricingScheme': OneOf(
            [
                LeafType(PricingSchemeEnum)
            ]
        ),
        'MeteredComponentUnitPrice': OneOf(
            [
                LeafType(str),
                LeafType(float)
            ],
            Context.create(
               is_optional=True
            )
        ),
        'CreateComponentPriceUnitPrice': OneOf(
            [
                LeafType(str),
                LeafType(float)
            ],
            Context.create(
               is_optional=True
            )
        ),
        'QuantityBasedComponentPricingScheme': OneOf(
            [
                LeafType(PricingSchemeEnum)
            ]
        ),
        'QuantityBasedComponentUnitPrice': OneOf(
            [
                LeafType(str),
                LeafType(float)
            ],
            Context.create(
               is_optional=True
            )
        ),
        'OnOffComponentPricingScheme': OneOf(
            [
                LeafType(PricingSchemeEnum)
            ]
        ),
        'OnOffComponentUnitPrice': OneOf(
            [
                LeafType(str),
                LeafType(float)
            ],
            Context.create(
               is_optional=True
            )
        ),
        'PrepaidUsageComponentPricingScheme': OneOf(
            [
                LeafType(PricingSchemeEnum)
            ],
            Context.create(
               is_optional=True
            )
        ),
        'PrepaidUsageComponentUnitPrice': OneOf(
            [
                LeafType(str),
                LeafType(float)
            ],
            Context.create(
               is_optional=True
            )
        ),
        'PrepaidUsageComponentExpirationIntervalUnit': OneOf(
            [
                LeafType(IntervalUnitEnum)
            ],
            Context.create(
               is_optional=True
            )
        ),
        'OveragePricingPricingScheme': OneOf(
            [
                LeafType(PricingSchemeEnum)
            ]
        ),
        'OveragePricingPrices': OneOf(
            [
                LeafType(Price,
                         Context.create(
                             is_array=True
                         ))
            ],
            Context.create(
               is_array=True,
               is_optional=True
            )
        ),
        'PriceStartingQuantity': OneOf(
            [
                LeafType(int),
                LeafType(str)
            ]
        ),
        'PriceEndingQuantity': OneOf(
            [
                LeafType(int),
                LeafType(str)
            ],
            Context.create(
               is_optional=True,
               is_nullable=True
            )
        ),
        'PriceUnitPrice': OneOf(
            [
                LeafType(int),
                LeafType(str)
            ]
        ),
        'EBBComponentPricingScheme': OneOf(
            [
                LeafType(PricingSchemeEnum)
            ]
        ),
        'EBBComponentUnitPrice': OneOf(
            [
                LeafType(str),
                LeafType(float)
            ],
            Context.create(
               is_optional=True
            )
        ),
        'CreateComponentPricePointRequestPricePoint': AnyOf(
            [
                LeafType(CreateComponentPricePoint),
                LeafType(CreatePrepaidUsageComponentPricePoint)
            ]
        ),
        'CreatePrepaidUsageComponentPricePointExpirationIntervalUnit': OneOf(
            [
                LeafType(IntervalUnitEnum)
            ],
            Context.create(
               is_optional=True
            )
        ),
        'PricePointExpirationIntervalUnit': OneOf(
            [
                LeafType(IntervalUnitEnum)
            ],
            Context.create(
               is_optional=True
            )
        ),
        'CreateComponentPricePointsRequestPricePoints': AnyOf(
            [
                LeafType(CreateComponentPricePoint),
                LeafType(CreatePrepaidUsageComponentPricePoint)
            ],
            Context.create(
               is_array=True
            )
        ),
        'CreatePaymentProfileExpirationMonth': OneOf(
            [
                LeafType(int),
                LeafType(str)
            ],
            Context.create(
               is_optional=True
            )
        ),
        'CreatePaymentProfileExpirationYear': OneOf(
            [
                LeafType(int),
                LeafType(str)
            ],
            Context.create(
               is_optional=True
            )
        ),
        'ReadPaymentProfileResponsePaymentProfile': OneOf(
            [
                LeafType(BankAccountPaymentProfile),
                LeafType(CreditCardPaymentProfile)
            ]
        ),
        'RefundInvoiceRequestRefund': AnyOf(
            [
                LeafType(RefundInvoice),
                LeafType(RefundConsolidatedInvoice)
            ]
        ),
        'RefundConsolidatedInvoiceSegmentUids': OneOf(
            [
                LeafType(str,
                         Context.create(
                             is_array=True
                         )),
                LeafType(str)
            ]
        ),
        'RefundSegmentUids': OneOf(
            [
                LeafType(str,
                         Context.create(
                             is_array=True
                         )),
                LeafType(str)
            ],
            Context.create(
               is_optional=True
            )
        ),
        'InvoiceEventEventData': AnyOf(
            [
                LeafType(ApplyPaymentEventData)
            ],
            Context.create(
               is_optional=True
            )
        ),
        'CreateInvoicePaymentAmount': OneOf(
            [
                LeafType(str),
                LeafType(float)
            ],
            Context.create(
               is_optional=True
            )
        ),
        'CreateMultiInvoicePaymentAmount': OneOf(
            [
                LeafType(str),
                LeafType(float)
            ]
        ),
        'SubscriptionComponentPricePointType': OneOf(
            [
                LeafType(PricePointTypeEnum)
            ],
            Context.create(
               is_optional=True
            )
        ),
        'ComponentSPricePointAssignmentPricePoint': OneOf(
            [
                LeafType(str),
                LeafType(int)
            ],
            Context.create(
               is_optional=True
            )
        ),
        'CreateAllocationQuantity': OneOf(
            [
                LeafType(int),
                LeafType(float)
            ]
        ),
        'CreateAllocationPricePointId': OneOf(
            [
                LeafType(str),
                LeafType(int)
            ],
            Context.create(
               is_optional=True,
               is_nullable=True
            )
        ),
        'AllocationPayment': AnyOf(
            [
                LeafType(AllocationPayment)
            ],
            Context.create(
               is_optional=True
            )
        ),
        'AllocationPreviewItemQuantity': OneOf(
            [
                LeafType(float),
                LeafType(int)
            ],
            Context.create(
               is_optional=True
            )
        ),
        'CreateUsageQuantity': OneOf(
            [
                LeafType(int),
                LeafType(float)
            ],
            Context.create(
               is_optional=True
            )
        ),
        'UsageQuantity': OneOf(
            [
                LeafType(int),
                LeafType(str)
            ],
            Context.create(
               is_optional=True
            )
        ),
        'CreateSubscriptionComponents': OneOf(
            [
                LeafType(CreateSubscriptionComponent)
            ],
            Context.create(
               is_array=True,
               is_optional=True
            )
        ),
        'CreateSubscriptionGroup': OneOf(
            [
                LeafType(GroupSettings),
                LeafType(bool)
            ],
            Context.create(
               is_optional=True
            )
        ),
        'CreateSubscriptionOfferId': OneOf(
            [
                LeafType(str),
                LeafType(int)
            ],
            Context.create(
               is_optional=True
            )
        ),
        'CustomPriceUsedForSubscriptionCreateUpdatePriceInCents': OneOf(
            [
                LeafType(str),
                LeafType(int)
            ],
            Context.create(
               is_optional=True
            )
        ),
        'CustomPriceUsedForSubscriptionCreateUpdateInterval': OneOf(
            [
                LeafType(str),
                LeafType(int)
            ],
            Context.create(
               is_optional=True
            )
        ),
        'CustomPriceUsedForSubscriptionCreateUpdateIntervalUnit': OneOf(
            [
                LeafType(IntervalUnitEnum)
            ],
            Context.create(
               is_optional=True
            )
        ),
        'CustomPriceUsedForSubscriptionCreateUpdateTrialPriceInCents': OneOf(
            [
                LeafType(str),
                LeafType(int)
            ],
            Context.create(
               is_optional=True
            )
        ),
        'CustomPriceUsedForSubscriptionCreateUpdateTrialInterval': OneOf(
            [
                LeafType(str),
                LeafType(int)
            ],
            Context.create(
               is_optional=True
            )
        ),
        'CustomPriceUsedForSubscriptionCreateUpdateTrialIntervalUnit': OneOf(
            [
                LeafType(IntervalUnitEnum)
            ],
            Context.create(
               is_optional=True
            )
        ),
        'CustomPriceUsedForSubscriptionCreateUpdateInitialChargeInCents': OneOf(
            [
                LeafType(str),
                LeafType(int)
            ],
            Context.create(
               is_optional=True
            )
        ),
        'CustomPriceUsedForSubscriptionCreateUpdateExpirationInterval': OneOf(
            [
                LeafType(str),
                LeafType(int)
            ],
            Context.create(
               is_optional=True
            )
        ),
        'CustomPriceUsedForSubscriptionCreateUpdateExpirationIntervalUnit': OneOf(
            [
                LeafType(IntervalUnitEnum)
            ],
            Context.create(
               is_optional=True
            )
        ),
        'PaymentProfileAttributesExpirationMonth': OneOf(
            [
                LeafType(int),
                LeafType(str)
            ],
            Context.create(
               is_optional=True
            )
        ),
        'PaymentProfileAttributesExpirationYear': OneOf(
            [
                LeafType(int),
                LeafType(str)
            ],
            Context.create(
               is_optional=True
            )
        ),
        'CreateSubscriptionComponentComponentId': OneOf(
            [
                LeafType(int),
                LeafType(str)
            ],
            Context.create(
               is_optional=True
            )
        ),
        'CreateSubscriptionComponentPricePointId': OneOf(
            [
                LeafType(int),
                LeafType(str)
            ],
            Context.create(
               is_optional=True
            )
        ),
        'ComponentCustomPricePricingScheme': OneOf(
            [
                LeafType(PricingSchemeEnum)
            ],
            Context.create(
               is_optional=True
            )
        ),
        'CalendarBillingSnapDay': OneOf(
            [
                LeafType(int),
                LeafType(str)
            ],
            Context.create(
               is_optional=True
            )
        ),
        'UpdateSubscriptionSnapDay': OneOf(
            [
                LeafType(SnapDayEnum),
                LeafType(int)
            ],
            Context.create(
               is_optional=True
            )
        ),
        'UpdateSubscriptionNetTerms': OneOf(
            [
                LeafType(str),
                LeafType(int)
            ],
            Context.create(
               is_optional=True
            )
        ),
        'ReactivateSubscriptionRequestResume': OneOf(
            [
                LeafType(bool),
                LeafType(ResumeOptions)
            ],
            Context.create(
               is_optional=True
            )
        ),
        'RenewalPreviewComponentComponentId': OneOf(
            [
                LeafType(str),
                LeafType(int)
            ],
            Context.create(
               is_optional=True
            )
        ),
        'RenewalPreviewComponentPricePointId': OneOf(
            [
                LeafType(str),
                LeafType(int)
            ],
            Context.create(
               is_optional=True
            )
        ),
        'CreateInvoiceItemQuantity': OneOf(
            [
                LeafType(float),
                LeafType(str)
            ],
            Context.create(
               is_optional=True
            )
        ),
        'CreateInvoiceItemUnitPrice': OneOf(
            [
                LeafType(float),
                LeafType(str)
            ],
            Context.create(
               is_optional=True
            )
        ),
        'CreateInvoiceItemProductId': OneOf(
            [
                LeafType(str),
                LeafType(int)
            ],
            Context.create(
               is_optional=True
            )
        ),
        'CreateInvoiceItemComponentId': OneOf(
            [
                LeafType(str),
                LeafType(int)
            ],
            Context.create(
               is_optional=True
            )
        ),
        'CreateInvoiceItemPricePointId': OneOf(
            [
                LeafType(str),
                LeafType(int)
            ],
            Context.create(
               is_optional=True
            )
        ),
        'CreateInvoiceItemProductPricePointId': OneOf(
            [
                LeafType(str),
                LeafType(int)
            ],
            Context.create(
               is_optional=True
            )
        ),
        'CreateInvoiceCouponPercentage': OneOf(
            [
                LeafType(str),
                LeafType(float)
            ],
            Context.create(
               is_optional=True
            )
        ),
        'CreateInvoiceCouponAmount': OneOf(
            [
                LeafType(str),
                LeafType(float)
            ],
            Context.create(
               is_optional=True
            )
        ),
        'CreateInvoiceCouponProductFamilyId': OneOf(
            [
                LeafType(str),
                LeafType(int)
            ],
            Context.create(
               is_optional=True
            )
        ),
        'CreateInvoiceCouponCompoundingStrategy': OneOf(
            [
                LeafType(CompoundingStrategyEnum)
            ],
            Context.create(
               is_optional=True
            )
        ),
        'IssueServiceCreditAmount': OneOf(
            [
                LeafType(float),
                LeafType(str)
            ]
        ),
        'DeductServiceCreditAmount': OneOf(
            [
                LeafType(str),
                LeafType(float)
            ]
        ),
        'SubscriptionGroupCreditCardFullNumber': OneOf(
            [
                LeafType(str),
                LeafType(int)
            ],
            Context.create(
               is_optional=True
            )
        ),
        'SubscriptionGroupCreditCardExpirationMonth': OneOf(
            [
                LeafType(str),
                LeafType(int)
            ],
            Context.create(
               is_optional=True
            )
        ),
        'SubscriptionGroupCreditCardExpirationYear': OneOf(
            [
                LeafType(str),
                LeafType(int)
            ],
            Context.create(
               is_optional=True
            )
        ),
        'SubscriptionGroupSignupComponentComponentId': OneOf(
            [
                LeafType(str),
                LeafType(int)
            ],
            Context.create(
               is_optional=True
            )
        ),
        'SubscriptionGroupSignupComponentAllocatedQuantity': OneOf(
            [
                LeafType(str),
                LeafType(int)
            ],
            Context.create(
               is_optional=True
            )
        ),
        'SubscriptionGroupSignupComponentUnitBalance': OneOf(
            [
                LeafType(str),
                LeafType(int)
            ],
            Context.create(
               is_optional=True
            )
        ),
        'SubscriptionGroupSignupComponentPricePointId': OneOf(
            [
                LeafType(str),
                LeafType(int)
            ],
            Context.create(
               is_optional=True
            )
        ),
        'SubscriptionGroupComponentCustomPricePricingScheme': OneOf(
            [
                LeafType(PricingSchemeEnum)
            ],
            Context.create(
               is_optional=True
            )
        ),
        'CreateSubscriptionGroupSubscriptionId': OneOf(
            [
                LeafType(str),
                LeafType(int)
            ]
        ),
        'AddSubscriptionToAGroupGroup': OneOf(
            [
                LeafType(GroupSettings),
                LeafType(bool)
            ],
            Context.create(
               is_optional=True
            )
        ),
        'CreateSegmentSegmentProperty1Value': OneOf(
            [
                LeafType(str),
                LeafType(float),
                LeafType(int),
                LeafType(bool)
            ],
            Context.create(
               is_optional=True
            )
        ),
        'CreateSegmentSegmentProperty2Value': OneOf(
            [
                LeafType(str),
                LeafType(float),
                LeafType(int),
                LeafType(bool)
            ],
            Context.create(
               is_optional=True
            )
        ),
        'CreateSegmentSegmentProperty3Value': OneOf(
            [
                LeafType(str),
                LeafType(float),
                LeafType(int),
                LeafType(bool)
            ],
            Context.create(
               is_optional=True
            )
        ),
        'CreateSegmentSegmentProperty4Value': OneOf(
            [
                LeafType(str),
                LeafType(float),
                LeafType(int),
                LeafType(bool)
            ],
            Context.create(
               is_optional=True
            )
        ),
        'CreateOrUpdateSegmentPriceUnitPrice': OneOf(
            [
                LeafType(str),
                LeafType(float)
            ]
        ),
        'SegmentSegmentProperty1Value': OneOf(
            [
                LeafType(str),
                LeafType(float),
                LeafType(int),
                LeafType(bool)
            ],
            Context.create(
               is_optional=True
            )
        ),
        'SegmentSegmentProperty2Value': OneOf(
            [
                LeafType(str),
                LeafType(float),
                LeafType(int),
                LeafType(bool)
            ],
            Context.create(
               is_optional=True
            )
        ),
        'SegmentSegmentProperty3Value': OneOf(
            [
                LeafType(str),
                LeafType(float),
                LeafType(int),
                LeafType(bool)
            ],
            Context.create(
               is_optional=True
            )
        ),
        'SegmentSegmentProperty4Value': OneOf(
            [
                LeafType(str),
                LeafType(float),
                LeafType(int),
                LeafType(bool)
            ],
            Context.create(
               is_optional=True
            )
        ),
        'RefundPrepaymentAmount': OneOf(
            [
                LeafType(str),
                LeafType(float)
            ]
        )
    }

    @staticmethod
    def get(name):
        return UnionTypeLookUp._templates[name]

