FROM python:3.11

COPY . ./app
WORKDIR /app

RUN pip install -r requirements.txt
RUN pip install -r test-requirements.txt

ARG SUBDOMAIN
ARG DOMAIN
ARG BASIC_AUTH_USERNAME
ARG BASIC_AUTH_PASSWORD

ENV SUBDOMAIN=${SUBDOMAIN}
ENV DOMAIN=${DOMAIN}
ENV BASIC_AUTH_USERNAME=${BASIC_AUTH_USERNAME}
ENV BASIC_AUTH_PASSWORD=${BASIC_AUTH_PASSWORD}

CMD ["pytest", "tests/"]
