# -*- coding: utf-8 -*-

"""
maxioadvancedbillingformerlychargifyapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class BankAccountVaultEnum(object):

    """Implementation of the 'Bank Account Vault' enum.

    The vault that stores the payment profile with the provided vault_token.

    Attributes:
        AUTHORIZENET: TODO: type description here.
        STRIPE: TODO: type description here.

    """
    AUTHORIZENET = 'authorizenet'

    STRIPE = 'stripe'

