# -*- coding: utf-8 -*-

"""
maxioadvancedbillingformerlychargifyapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class BankAccountTypeEnum(object):

    """Implementation of the 'Bank Account Type' enum.

    TODO: type enum description here.

    Attributes:
        CHECKING: TODO: type description here.
        SAVINGS: TODO: type description here.

    """
    CHECKING = 'checking'

    SAVINGS = 'savings'

