# -*- coding: utf-8 -*-

"""
maxioadvancedbillingformerlychargifyapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class BasicDateFieldEnum(object):

    """Implementation of the 'Basic Date Field' enum.

    Allows to filter by `created_at` or `updated_at`.

    Attributes:
        UPDATED_AT: TODO: type description here.
        CREATED_AT: TODO: type description here.

    """
    UPDATED_AT = 'updated_at'

    CREATED_AT = 'created_at'

