# -*- coding: utf-8 -*-

"""
maxioadvancedbillingformerlychargifyapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from maxioadvancedbillingformerlychargifyapi.api_helper import APIHelper


class ComponentPricePointPrice(object):

    """Implementation of the 'Component Price Point Price' model.

    TODO: type model description here.

    Attributes:
        id (int): TODO: type description here.
        component_id (int): TODO: type description here.
        starting_quantity (int): TODO: type description here.
        ending_quantity (int): TODO: type description here.
        unit_price (str): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "id": 'id',
        "component_id": 'component_id',
        "starting_quantity": 'starting_quantity',
        "ending_quantity": 'ending_quantity',
        "unit_price": 'unit_price'
    }

    _optionals = [
        'id',
        'component_id',
        'starting_quantity',
        'ending_quantity',
        'unit_price',
    ]

    _nullables = [
        'ending_quantity',
    ]

    def __init__(self,
                 id=APIHelper.SKIP,
                 component_id=APIHelper.SKIP,
                 starting_quantity=APIHelper.SKIP,
                 ending_quantity=APIHelper.SKIP,
                 unit_price=APIHelper.SKIP):
        """Constructor for the ComponentPricePointPrice class"""

        # Initialize members of the class
        if id is not APIHelper.SKIP:
            self.id = id 
        if component_id is not APIHelper.SKIP:
            self.component_id = component_id 
        if starting_quantity is not APIHelper.SKIP:
            self.starting_quantity = starting_quantity 
        if ending_quantity is not APIHelper.SKIP:
            self.ending_quantity = ending_quantity 
        if unit_price is not APIHelper.SKIP:
            self.unit_price = unit_price 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        id = dictionary.get("id") if dictionary.get("id") else APIHelper.SKIP
        component_id = dictionary.get("component_id") if dictionary.get("component_id") else APIHelper.SKIP
        starting_quantity = dictionary.get("starting_quantity") if dictionary.get("starting_quantity") else APIHelper.SKIP
        ending_quantity = dictionary.get("ending_quantity") if "ending_quantity" in dictionary.keys() else APIHelper.SKIP
        unit_price = dictionary.get("unit_price") if dictionary.get("unit_price") else APIHelper.SKIP
        # Return an object of this model
        return cls(id,
                   component_id,
                   starting_quantity,
                   ending_quantity,
                   unit_price)
