# -*- coding: utf-8 -*-

"""
maxioadvancedbillingformerlychargifyapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class ComponentKindPathEnum(object):

    """Implementation of the 'Component Kind Path' enum.

    TODO: type enum description here.

    Attributes:
        METERED_COMPONENTS: TODO: type description here.
        QUANTITY_BASED_COMPONENTS: TODO: type description here.
        ON_OFF_COMPONENTS: TODO: type description here.
        PREPAID_USAGE_COMPONENTS: TODO: type description here.
        EVENT_BASED_COMPONENTS: TODO: type description here.

    """
    METERED_COMPONENTS = 'metered_components'

    QUANTITY_BASED_COMPONENTS = 'quantity_based_components'

    ON_OFF_COMPONENTS = 'on_off_components'

    PREPAID_USAGE_COMPONENTS = 'prepaid_usage_components'

    EVENT_BASED_COMPONENTS = 'event_based_components'

