# -*- coding: utf-8 -*-

"""
maxioadvancedbillingformerlychargifyapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class CreditTypeEnum(object):

    """Implementation of the 'Credit Type' enum.

    The type of charge to be applied when a component is upgraded. Valid
    values are: `prorated`, `full`, `none`.

    Attributes:
        FULL: TODO: type description here.
        PRORATED: TODO: type description here.
        NONE: TODO: type description here.

    """
    FULL = 'full'

    PRORATED = 'prorated'

    NONE = 'none'

