# -*- coding: utf-8 -*-

"""
maxioadvancedbillingformerlychargifyapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class CurrencyPriceRoleEnum(object):

    """Implementation of the 'Currency Price Role' enum.

    Role for the price.

    Attributes:
        BASELINE: TODO: type description here.
        TRIAL: TODO: type description here.
        INITIAL: TODO: type description here.

    """
    BASELINE = 'baseline'

    TRIAL = 'trial'

    INITIAL = 'initial'

