# -*- coding: utf-8 -*-

"""
maxioadvancedbillingformerlychargifyapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from maxioadvancedbillingformerlychargifyapi.models.segments_1 import Segments1


class Errors13(object):

    """Implementation of the 'Errors13' model.

    TODO: type model description here.

    Attributes:
        segments (Segments1): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "segments": 'segments'
    }

    def __init__(self,
                 segments=None):
        """Constructor for the Errors13 class"""

        # Initialize members of the class
        self.segments = segments 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        segments = Segments1.from_dictionary(dictionary.get('segments')) if dictionary.get('segments') else None
        # Return an object of this model
        return cls(segments)
