# -*- coding: utf-8 -*-

"""
maxioadvancedbillingformerlychargifyapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from maxioadvancedbillingformerlychargifyapi.api_helper import APIHelper
from maxioadvancedbillingformerlychargifyapi.models.member import Member


class Errors8(object):

    """Implementation of the 'Errors8' model.

    TODO: type model description here.

    Attributes:
        members (List[Member]): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "members": 'members'
    }

    _optionals = [
        'members',
    ]

    def __init__(self,
                 members=APIHelper.SKIP):
        """Constructor for the Errors8 class"""

        # Initialize members of the class
        if members is not APIHelper.SKIP:
            self.members = members 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        members = None
        if dictionary.get('members') is not None:
            members = [Member.from_dictionary(x) for x in dictionary.get('members')]
        else:
            members = APIHelper.SKIP
        # Return an object of this model
        return cls(members)
