# -*- coding: utf-8 -*-

"""
maxioadvancedbillingformerlychargifyapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from maxioadvancedbillingformerlychargifyapi.api_helper import APIHelper


class Errors2(object):

    """Implementation of the 'Errors2' model.

    TODO: type model description here.

    Attributes:
        component_id (float): TODO: type description here.
        price_point (float): TODO: type description here.
        message (str): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "component_id": 'component_id',
        "price_point": 'price_point',
        "message": 'message'
    }

    _optionals = [
        'component_id',
        'price_point',
        'message',
    ]

    def __init__(self,
                 component_id=APIHelper.SKIP,
                 price_point=APIHelper.SKIP,
                 message=APIHelper.SKIP):
        """Constructor for the Errors2 class"""

        # Initialize members of the class
        if component_id is not APIHelper.SKIP:
            self.component_id = component_id 
        if price_point is not APIHelper.SKIP:
            self.price_point = price_point 
        if message is not APIHelper.SKIP:
            self.message = message 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        component_id = dictionary.get("component_id") if dictionary.get("component_id") else APIHelper.SKIP
        price_point = dictionary.get("price_point") if dictionary.get("price_point") else APIHelper.SKIP
        message = dictionary.get("message") if dictionary.get("message") else APIHelper.SKIP
        # Return an object of this model
        return cls(component_id,
                   price_point,
                   message)
