# -*- coding: utf-8 -*-

"""
maxioadvancedbillingformerlychargifyapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class GroupTargetTypeEnum(object):

    """Implementation of the 'Group Target Type' enum.

    The type of object indicated by the id attribute.

    Attributes:
        CUSTOMER: TODO: type description here.
        SUBSCRIPTION: TODO: type description here.
        SELF: TODO: type description here.
        PARENT: TODO: type description here.
        ELDEST: TODO: type description here.

    """
    CUSTOMER = 'customer'

    SUBSCRIPTION = 'subscription'

    SELF = 'self'

    PARENT = 'parent'

    ELDEST = 'eldest'

