# -*- coding: utf-8 -*-

"""
maxioadvancedbillingformerlychargifyapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class HolderTypeEnum(object):

    """Implementation of the 'Holder Type' enum.

    TODO: type enum description here.

    Attributes:
        PERSONAL: TODO: type description here.
        BUSINESS: TODO: type description here.

    """
    PERSONAL = 'personal'

    BUSINESS = 'business'

