# -*- coding: utf-8 -*-

"""
maxioadvancedbillingformerlychargifyapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class IncludeNotNullEnum(object):

    """Implementation of the 'Include Not Null' enum.

    Passed as a parameter to list methods to return only non null values.

    Attributes:
        NOT_NULL: TODO: type description here.

    """
    NOT_NULL = 'not_null'

