# -*- coding: utf-8 -*-

"""
maxioadvancedbillingformerlychargifyapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class IncludeOptionEnum(object):

    """Implementation of the 'Include Option' enum.

    TODO: type enum description here.

    Attributes:
        EXCLUDE: TODO: type description here.
        INCLUDE: TODO: type description here.

    """
    EXCLUDE = '0'

    INCLUDE = '1'

