# -*- coding: utf-8 -*-

"""
maxioadvancedbillingformerlychargifyapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class InvoiceEventTypeEnum(object):

    """Implementation of the 'Invoice Event Type' enum.

    Invoice Event Type

    Attributes:
        ISSUE_INVOICE: TODO: type description here.
        APPLY_CREDIT_NOTE: TODO: type description here.
        APPLY_PAYMENT: TODO: type description here.
        REFUND_INVOICE: TODO: type description here.
        VOID_INVOICE: TODO: type description here.
        VOID_REMAINDER: TODO: type description here.
        BACKPORT_INVOICE: TODO: type description here.
        CHANGE_INVOICE_STATUS: TODO: type description here.
        CHANGE_INVOICE_COLLECTION_METHOD: TODO: type description here.
        REMOVE_PAYMENT: TODO: type description here.

    """
    ISSUE_INVOICE = 'issue_invoice'

    APPLY_CREDIT_NOTE = 'apply_credit_note'

    APPLY_PAYMENT = 'apply_payment'

    REFUND_INVOICE = 'refund_invoice'

    VOID_INVOICE = 'void_invoice'

    VOID_REMAINDER = 'void_remainder'

    BACKPORT_INVOICE = 'backport_invoice'

    CHANGE_INVOICE_STATUS = 'change_invoice_status'

    CHANGE_INVOICE_COLLECTION_METHOD = 'change_invoice_collection_method'

    REMOVE_PAYMENT = 'remove_payment'

