# -*- coding: utf-8 -*-

"""
maxioadvancedbillingformerlychargifyapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class ListSubscriptionGroupPrepaymentDateFieldEnum(object):

    """Implementation of the 'List Subscription Group Prepayment Date Field' enum.

    TODO: type enum description here.

    Attributes:
        CREATED_AT: TODO: type description here.
        APPLICATION_AT: TODO: type description here.

    """
    CREATED_AT = 'created_at'

    APPLICATION_AT = 'application_at'

