# -*- coding: utf-8 -*-

"""
maxioadvancedbillingformerlychargifyapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class ListSubscriptionComponentsSortEnum(object):

    """Implementation of the 'List Subscription Components Sort' enum.

    TODO: type enum description here.

    Attributes:
        ID: TODO: type description here.
        UPDATED_AT: TODO: type description here.

    """
    ID = 'id'

    UPDATED_AT = 'updated_at'

