# -*- coding: utf-8 -*-

"""
maxioadvancedbillingformerlychargifyapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class ListSubscriptionComponentsDateFieldEnum(object):

    """Implementation of the 'List Subscription Components Date Field' enum.

    TODO: type enum description here.

    Attributes:
        UPDATED_AT: TODO: type description here.

    """
    UPDATED_AT = 'updated_at'

