# -*- coding: utf-8 -*-

"""
maxioadvancedbillingformerlychargifyapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class ListProductsIncludeEnum(object):

    """Implementation of the 'List Products Include' enum.

    TODO: type enum description here.

    Attributes:
        PREPAID_PRODUCT_PRICE_POINT: TODO: type description here.

    """
    PREPAID_PRODUCT_PRICE_POINT = 'prepaid_product_price_point'

