# -*- coding: utf-8 -*-

"""
maxioadvancedbillingformerlychargifyapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from maxioadvancedbillingformerlychargifyapi.api_helper import APIHelper
from maxioadvancedbillingformerlychargifyapi.models.product_family import ProductFamily


class ProductFamilyResponse(object):

    """Implementation of the 'Product Family Response' model.

    TODO: type model description here.

    Attributes:
        product_family (ProductFamily): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "product_family": 'product_family'
    }

    _optionals = [
        'product_family',
    ]

    def __init__(self,
                 product_family=APIHelper.SKIP):
        """Constructor for the ProductFamilyResponse class"""

        # Initialize members of the class
        if product_family is not APIHelper.SKIP:
            self.product_family = product_family 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        product_family = ProductFamily.from_dictionary(dictionary.get('product_family')) if 'product_family' in dictionary.keys() else APIHelper.SKIP
        # Return an object of this model
        return cls(product_family)
