# -*- coding: utf-8 -*-

"""
maxioadvancedbillingformerlychargifyapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class ReactivationChargeEnum(object):

    """Implementation of the 'Reactivation Charge' enum.

    You may choose how to handle the reactivation charge for that
    subscription: 1) `prorated` A prorated charge for the product price will
    be attempted for to complete the period 2) `immediate` A full-price charge
    for the product price will be attempted immediately 3) `delayed` A
    full-price charge for the product price will be attempted at the next
    renewal

    Attributes:
        PRORATED: TODO: type description here.
        IMMEDIATE: TODO: type description here.
        DELAYED: TODO: type description here.

    """
    PRORATED = 'prorated'

    IMMEDIATE = 'immediate'

    DELAYED = 'delayed'

