# -*- coding: utf-8 -*-

"""
maxioadvancedbillingformerlychargifyapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class ResourceTypeEnum(object):

    """Implementation of the 'Resource Type' enum.

    TODO: type enum description here.

    Attributes:
        SUBSCRIPTIONS: TODO: type description here.
        CUSTOMERS: TODO: type description here.

    """
    SUBSCRIPTIONS = 'subscriptions'

    CUSTOMERS = 'customers'

