# -*- coding: utf-8 -*-

"""
maxioadvancedbillingformerlychargifyapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class ResumptionChargeEnum(object):

    """Implementation of the 'Resumption Charge' enum.

    (For calendar billing subscriptions only) The way that the resumed
    subscription's charge should be handled

    Attributes:
        PRORATED: TODO: type description here.
        IMMEDIATE: TODO: type description here.
        DELAYED: TODO: type description here.

    """
    PRORATED = 'prorated'

    IMMEDIATE = 'immediate'

    DELAYED = 'delayed'

