# -*- coding: utf-8 -*-

"""
maxioadvancedbillingformerlychargifyapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class ServiceCreditTypeEnum(object):

    """Implementation of the 'Service Credit Type' enum.

    The type of entry

    Attributes:
        CREDIT: TODO: type description here.
        DEBIT: TODO: type description here.

    """
    CREDIT = 'Credit'

    DEBIT = 'Debit'

