# -*- coding: utf-8 -*-

"""
maxioadvancedbillingformerlychargifyapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class SignupCollectionMethodEnum(object):

    """Implementation of the 'Signup Collection Method' enum.

    TODO: type enum description here.

    Attributes:
        REMITTANCE: TODO: type description here.
        AUTOMATIC: TODO: type description here.

    """
    REMITTANCE = 'remittance'

    AUTOMATIC = 'automatic'

