# -*- coding: utf-8 -*-

"""
maxioadvancedbillingformerlychargifyapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class StatusEnum(object):

    """Implementation of the 'Status' enum.

    The current status of the invoice. See [Invoice
    Statuses](https://chargify.zendesk.com/hc/en-us/articles/4407737494171#line
    -item-breakdowns) for more.

    Attributes:
        DRAFT: TODO: type description here.
        OPEN: TODO: type description here.
        PAID: TODO: type description here.
        PENDING: TODO: type description here.
        VOIDED: TODO: type description here.
        CANCELED: TODO: type description here.

    """
    DRAFT = 'draft'

    OPEN = 'open'

    PAID = 'paid'

    PENDING = 'pending'

    VOIDED = 'voided'

    CANCELED = 'canceled'

