# -*- coding: utf-8 -*-

"""
maxioadvancedbillingformerlychargifyapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class SubscriptionSortEnum(object):

    """Implementation of the 'Subscription Sort' enum.

    TODO: type enum description here.

    Attributes:
        SIGNUP_DATE: TODO: type description here.
        PERIOD_START: TODO: type description here.
        PERIOD_END: TODO: type description here.
        NEXT_ASSESSMENT: TODO: type description here.
        UPDATED_AT: TODO: type description here.
        CREATED_AT: TODO: type description here.

    """
    SIGNUP_DATE = 'signup_date'

    PERIOD_START = 'period_start'

    PERIOD_END = 'period_end'

    NEXT_ASSESSMENT = 'next_assessment'

    UPDATED_AT = 'updated_at'

    CREATED_AT = 'created_at'

