# -*- coding: utf-8 -*-

"""
maxioadvancedbillingformerlychargifyapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class SubscriptionIncludeEnum(object):

    """Implementation of the 'Subscription Include' enum.

    TODO: type enum description here.

    Attributes:
        COUPONS: TODO: type description here.
        SELF_SERVICE_PAGE_TOKEN: TODO: type description here.

    """
    COUPONS = 'coupons'

    SELF_SERVICE_PAGE_TOKEN = 'self_service_page_token'

