# -*- coding: utf-8 -*-

"""
maxioadvancedbillingformerlychargifyapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class SubscriptionGroupPrepaymentMethodEnum(object):

    """Implementation of the 'Subscription Group Prepayment Method' enum.

    TODO: type enum description here.

    Attributes:
        CHECK: TODO: type description here.
        CASH: TODO: type description here.
        MONEY_ORDER: TODO: type description here.
        ACH: TODO: type description here.
        PAYPAL_ACCOUNT: TODO: type description here.
        OTHER: TODO: type description here.

    """
    CHECK = 'check'

    CASH = 'cash'

    MONEY_ORDER = 'money_order'

    ACH = 'ach'

    PAYPAL_ACCOUNT = 'paypal_account'

    OTHER = 'other'

